wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1644826836
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      - 16
      4: 3.8.10
      5: 0.12.10
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 100
