wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1644728470
    t:
      1:
      - 3
      - 5
      4: 3.7.9
      5: 0.12.10
      8:
      - 1
      - 3
      - 5
