wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _wandb: {}
    batch_size: 128
    epochs: 100
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: '<Settings {''_args'': [''--ip=127.0.0.1'', ''--stdin=9003'', ''--control=9001'',
    ''--hb=9000'', ''--Session.signature_scheme="hmac-sha256"'', ''--Session.key=b"fb159545-4107-42b9-ae82-7bda0470a826"'',
    ''--shell=9002'', ''--transport="tcp"'', ''--iopub=9004'', ''--f=/tmp/tmp-17702VLRFX9BJasnT.json''],
    ''_cli_only_mode'': None, ''_config_dict'': None, ''_cuda'': None, ''_debug_log'':
    None, ''_disable_meta'': None, ''_disable_stats'': None, ''_disable_viewer'':
    None, ''_except_exit'': None, ''_executable'': ''/usr/bin/python3'', ''_internal_check_process'':
    8, ''_internal_queue_timeout'': 2, ''_jupyter_name'': None, ''_jupyter_path'':
    None, ''_jupyter_root'': None, ''_os'': ''Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29'',
    ''_python'': ''3.8.10'', ''_require_service'': None, ''_runqueue_item_id'': None,
    ''_save_requirements'': True, ''_service_transport'': None, ''_start_datetime'':
    datetime.datetime(2022, 2, 14, 7, 40, 1, 443192), ''_start_time'': 1644824401.443192,
    ''_tmp_code_dir'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/run-20220214_074001-269avj3e/tmp/code'',
    ''_unsaved_keys'': None, ''allow_val_change'': None, ''anonymous'': None, ''api_key'':
    ''***REDACTED***'', ''base_url'': ''https://api.wandb.ai'', ''code_dir'': None,
    ''config_paths'': None, ''console'': ''auto'', ''disable_code'': None, ''disable_git'':
    False, ''disabled'': False, ''docker'': None, ''email'': ''luis_costigan@hotmail.co.uk'',
    ''entity'': None, ''files_dir'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/run-20220214_074001-269avj3e/files'',
    ''force'': None, ''git_remote'': ''origin'', ''heartbeat_seconds'': 30, ''host'':
    ''bd231645c0d6'', ''ignore_globs'': (), ''label_disable'': None, ''launch'': None,
    ''launch_config_path'': None, ''log_dir'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/run-20220214_074001-269avj3e/logs'',
    ''log_internal'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/run-20220214_074001-269avj3e/logs/debug-internal.log'',
    ''log_symlink_internal'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/debug-internal.log'',
    ''log_symlink_user'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/debug.log'',
    ''log_user'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/run-20220214_074001-269avj3e/logs/debug.log'',
    ''login_timeout'': None, ''magic'': None, ''mode'': ''online'', ''notebook_name'':
    None, ''problem'': ''fatal'', ''program'': ''<python with no main file>'', ''program_relpath'':
    None, ''project'': ''house-price-prediction'', ''quiet'': None, ''reinit'': None,
    ''relogin'': None, ''resume'': None, ''resume_fname'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/wandb-resume.json'',
    ''root_dir'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow'',
    ''run_group'': None, ''run_id'': ''269avj3e'', ''run_job_type'': None, ''run_name'':
    None, ''run_notes'': None, ''run_tags'': None, ''sagemaker_disable'': None, ''save_code'':
    None, ''settings_system'': ''/root/.config/wandb/settings'', ''settings_workspace'':
    ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/settings'',
    ''show_colors'': None, ''show_emoji'': None, ''show_errors'': True, ''show_info'':
    True, ''show_warnings'': True, ''silent'': False, ''start_method'': None, ''strict'':
    None, ''summary_errors'': None, ''summary_warnings'': 5, ''sweep_id'': None, ''sweep_param_path'':
    None, ''symlink'': True, ''sync_dir'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/run-20220214_074001-269avj3e'',
    ''sync_file'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/run-20220214_074001-269avj3e/run-269avj3e.wandb'',
    ''sync_symlink_latest'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/latest-run'',
    ''system_sample'': 15, ''system_sample_seconds'': 2, ''tmp_dir'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/run-20220214_074001-269avj3e/tmp'',
    ''username'': ''root'', ''_console'': <SettingsConsole.WRAP: 1>, ''_jupyter'':
    True, ''_kaggle'': False, ''_noop'': False, ''_offline'': False, ''_quiet'': None,
    ''_show_info'': True, ''_show_warnings'': True, ''_show_errors'': True, ''_silent'':
    False, ''_strict'': None, ''_windows'': False, ''is_local'': False, ''run_mode'':
    ''run'', ''timespec'': ''20220214_074001'', ''wandb_dir'': ''/root/data-science-projects/house-price-prediction/Models/tensorflow/wandb/''}>'
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1644825838
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 16
      4: 3.8.10
      5: 0.12.10
      8:
      - 1
      - 5
